### ISSUE TITLE
Error while delete notifications

### ISSUE THREAD

**Issue by dhaval0122** [googlesamples/android-ActiveNotifications#1]
# Nexus5

com.example.android.activenotifications E/AndroidRuntime? FATAL EXCEPTION: main
    Process: com.example.android.activenotifications, PID: 15421
    java.lang.RuntimeException: Error receiving broadcast Intent { act=com.example.android.activenotifications.delete flg=0x10 } in com.example.android.activenotifications.ActiveNotificationActivity$1@578cede
            at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:878)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5401)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:725)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.content.pm.ParceledListSlice.getList()' on a null object reference
            at android.app.NotificationManager.getActiveNotifications(NotificationManager.java:701)
            at com.example.android.activenotifications.ActiveNotificationFragment.updateNumberOfNotifications(ActiveNotificationFragment.java:117)
            at com.example.android.activenotifications.ActiveNotificationActivity$1.onReceive(ActiveNotificationActivity.java:39)
            at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:868)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5401)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:725)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)

**Comment by pjcollins** [comment]
I'm able to reproduce this crash with the following steps:
1. Tap the "Add A Notification" button until there are ~15-20 active notifications.
2. Swipe the notification bar down and scroll to the bottom of the list of notifications.
3. Tap the button to clear all notifications.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
